### PR TITLE
Added weather icons

### PR DESCRIPTION
**Pull request by an0n981**

### CODE REVIEW

**Comment by M66B** [comment]
The wind icon looks different from the other icons. Could you please find a better matching wind icon?

Another things is that we need a "don't know" icon for unrecognized weather (there is a bug in slowing partly clouded might, which would better had resulted in an unknown icon instead of no notification).

**Comment by M66B** [comment]
The icons look nice! Where did you got them from? There needs to be an attribution note on GitHub for the icons.

**Comment by an0n981** [comment]
the icons are from iconarchive.com. According to what I have read on their site all icons are free to use, no attribution needed.

**Comment by an0n981** [comment]
"Another things is that we need a "don't know" icon for unrecognized weather (there is a bug in slowing partly clouded might, which would better had resulted in an unknown icon instead of no notification)."

Maybe something like a question mark?

**Comment by M66B** [comment]
I have already used the Android question mark, which is good enough for this purpose.
Thanks for the suggestion.

**Pull request closed without merging**
