### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by an0n981**

### CODE REVIEW

**Comment by M66B** [comment]
Thanks!

**Comment by M66B** [comment]
Test version: http://www.faircode.eu/BPT2-V0.32g.apk

**Comment by an0n981** [comment]
Settings - Altitude Correction "Tap for information..." showing in englisch. I can't find a string that needs changing.

**Comment by M66B** [comment]
It is not translatable, but I will change this.

**Comment by M66B** [comment]
It is changed now and I have updated the German translation as well ;-)

**Pull request merged**
