### PR TITLE
Update German translation

### PR DESCRIPTION
**Pull request by an0n981**

### CODE REVIEW

**Comment by M66B** [comment]
Please check this too: https://github.com/M66B/BackPackTrackII/commit/c2751e3ce63fb97b7a8f2413b018b88f5ab66e44

**Comment by an0n981** [comment]
that looks good, but somehow this commit got reverted to english

**Comment by an0n981** [comment]
disregard, it was just a different branch. the master is fine

**Comment by M66B** [comment]
Test version 1.8-5 with latest commits:
https://github.com/M66B/BackPackTrackII/releases/tag/1.8

**Pull request merged**
