### PR TITLE
Update strings.xml

### PR DESCRIPTION
**Pull request by an0n981**

### CODE REVIEW

**Comment by M66B** [comment]
Test version: http:/www.faircode.eu/BPT2-V0.39g.apk

**Comment by an0n981** [comment]
The google elevation points in altitude are not translatable

**Comment by M66B** [comment]
They are, search for "Google elevation" in the string resource values file.

**Comment by M66B** [comment]
There texts in total.

**Comment by M66B** [comment]
*Three

**Comment by an0n981** [comment]
You are right. My MacBook failed at searching

**Pull request merged**
