### PR TITLE
Initial German translation

### PR DESCRIPTION
**Pull request by an0n981**

### CODE REVIEW

**Comment by M66B** [comment]
Test version: http://www.faircode.eu/BPT2-V0.27g.apk
Please check the two commits above.

**Comment by M66B** [comment]
Ate the English texts okay for you?

**Comment by an0n981** [comment]
The English text are great. I can't actually check the German texts since AppSettings donesn't work on Lollipop.

**Comment by M66B** [comment]
You can always change the language setting of Android (temporarily).

**Comment by an0n981** [comment]
Touché, Yes German texts work.

**Comment by M66B** [comment]
I have done a small fix (see commit above):
http://www.faircode.eu/BPT2-V0.27g3.apk

Please check if the column headings in the location/activity/walk history do fit.

**Comment by M66B** [comment]
The fix will let you see the wind direction in the status bar notification title.

**Comment by an0n981** [comment]
g3 has some issues with heading. https://mega.nz/#!1hgjFQaY!7a5yYmwsV_e67InCOCyLlf2V6KJ1_Mi_y84ZwqpIffQ (can't upload here on mobile)

**Comment by M66B** [comment]
I was afraid for that, so try to abbreviate things.

**Comment by an0n981** [comment]
I'll see what can be done

**Comment by an0n981** [comment]
Since I can't verify everything without first spending a lot of time in XPrivacy, are all the strings that need looked at marked with header?

**Comment by M66B** [comment]
Yes, mainly these:

```
<string name="header_altitude">Alt.</string>
<string name="header_accuracy">Acc.</string>
<string name="header_distance">Dist.</string>
```

And the back pack man will return ;-)

**Comment by an0n981** [comment]
:)

**Pull request merged**
